spring:
  #  profiles:
  #    active: local
#  messages:
#    basename: messages,errors  # 에러메시지

  data:
    web:
      pageable:
        default-page-size: 20 # 기본 페이지 사이즈

  servlet:
    multipart:
      max-file-size: 50MB

      #enabled: false

  jpa:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true

# application 저장 후 자동 재시작 설정
#  devtools:
#    restart:
#      enabled: false

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace #띄어쓰기 2칸


server:
  servlet:
    session:
      timeout: 30m  # 세션 타임아웃 설정(분 단위 기준) 60(1분)
#      tracking-modes: cookie # url 전달 방식 끄고 항상 쿠키를 통해서만 세션 유지


  security:
    sessions:
      #      maximum-sessions: 1 # 동시 로그인 세션 수 제한 (1로 설정하면 하나의 사용자만 로그인 가능)
      max-sessions-prevents-login: false # 동시 로그인 시 로그인 거부 여부 설정 (false로 설정하면 동시 로그인이 불가능)
      session-fixation: migrateSession # 세션 고정 방지 설정
##      invalid-session-url: /login?timeout # 세션 만료 시 리다이렉트할 URL 설정

---
spring:
  profiles:
    active: local
  datasource:
    username: root
    password: 12341234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cook_study

  jpa:
    hibernate:
      ddl-auto: update  # create: 자동으로 테이블 만들어줌

file:
  dir: /Users/sooha/SpringWorkspace/cook/src/main/resources/static/files/