spring:
#  profiles:
#    active: local
  messages:
    basename: messages,errors  # 에러메시지

  data:
    web:
      pageable:
        default-page-size: 20 # 기본 페이지 사이즈

  servlet:
    multipart:
      max-file-size: 20MB

      #enabled: false

  jpa:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace #띄어쓰기 2칸


server:
  servlet:
    session:
      timeout: 1800  # 세션 타임아웃 설정(분 단위 기준) 60(1분)
      tracking-modes: cookie # url 전달 방식 끄고 항상 쿠키를 통해서만 세션 유지

---
spring:
  profiles:
    active: local
  datasource:
    username: root
    password: 12341234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cook_study

  jpa:
    hibernate:
      ddl-auto: update  # create: 자동으로 테이블 만들어줌

file:
  dir: /Users/sooha/SpringWorkspace/cook/src/main/resources/static/files/
---
spring:
  config:
    activate:
      on-profile: real
  datasource:
    url: jdbc:mariadb://springboot-webservice.c2fnuqugf4lp.ap-northeast-2.rds.amazonaws.com:3306/webservice
    username: sooha
    password: tngk1996*
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8080

file:
  dir: /home/ec2-user/app/files/
---