global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # 또는 your-container-name:8080, Docker 컨테이너에서 호스트 머신의 Spring Boot 앱(localhost:8080)에 접근할 때 사용하는 주소

#  - job_name: 'mysql_exporter'
#    static_configs:
#      - targets: [ 'mysql_exporter:9104' ]

#  - job_name: 'redis_exporter'
#    static_configs:
#      - targets: [ 'redis_exporter:9121' ]